debug: false
# 工作模式
# WEB_HOOK 或 POLLING_API
mode: WEB_HOOK
# 在 WEB_HOOK 模式（WebHook）下的配置
web_hook:
  # WebHook 端口号
  port: 8087
  # 接收地址，最终 WebHook 地址为
  # http://<你的服务器IP>:端口/接收地址
  # 建议将地址设置得尽量复杂，并且套 Cloudflare Tunnel，不要与服务器共用同一个二级域名
  path: /api/afdian/hook
  # 是否忽略执行所有提交上来的订单，用于测试 webhook 是否工作正常
  # 确认工作正常后，应该关闭此项
  ignore-all: true
  # 允许入站的白名单IP列表，留空则允许所有IP
  # 当首次访问 WebHook 的IP不在白名单时，在控制台输出警告
  whitelist: []
# 在 POLLING_API 模式（轮询API）下的配置
polling_api:
  # 多少秒轮询一次爱发电订单列表API
  period_seconds: 30
  # 一次拉取多少个订单，支持 1-100
  limit_count: 50
  # 是否忽略执行所有查询到的订单，用于初次安装插件、将 limit_order 调大、或从 WebHook 切换到此模式时，同步爱发电数据使用
  # 确认工作正常后，应该关闭此项
  ignore-all: true

player-name:
  # 订单备注去除首尾空格后，完全匹配这个正则表达式，才执行相应操作
  # 中文名：‘[a-zA-Z0-9_\u4e00-\u9fa5]*'
  # 英文名：‘[a-zA-Z0-9_]*'
  pattern: '[a-zA-Z0-9_]*'
  # 最小长度
  min-length: 3
  # 最大长度
  max-length: 20

# 收到一般赞助
product-normal:
  # 赞助金额处理（可选，默认为 10.0, floor）
  point:
    # 乘数
    scale: 10.0
    # 四舍五入方式
    # floor 向下取整，ceil 向上取整，round 四舍五入，
    # 输入数字即保留N位小数，比如2保留两位小数
    rounding: floor
  # 是否要求玩家在线（可选，默认为 false）
  require-online: false
  # 收到一般赞助执行的命令
  # [console]控制台命令
  # [player]玩家命令（如果玩家在线的话）
  # [message]提示玩家（如果玩家在线的话）
  # 由于收到订单完成通知时，玩家不一定在线，仅玩家在线时支持完整的 PAPI 变量，建议配合 require-online 使用
  # 可用的变量如下
  # %player% 为玩家名，
  # %money% 为原始金额（带两位小数点）
  # %point% 为处理后金额（按配置处理）
  # 以下变量仅在用户填写时有效，可能为空
  # %person% 联系方式 姓名
  # %phone% 联系方式 电话号码
  # %address% 联系方式 地址
  commands:
    - '[console]points give %player% %point%'
# 收到电铺订单
# 商品名称和型号名称均区分大小写
product-shop:
  # 商品名称，在爱发电创建的时候不要重名
  测试商品:
    # 型号名称
    测试型号:
      # 同 product-normal.point
      point:
        scale: 1.0
        rounding: floor
      # 同 product-normal.require-online
      require-online: false
      # 执行类型（可选，默认为 command）
      # point：point的值乘以购买数量，只执行一次 commands 列表
      # command：执行 购买数量 次数的 commands 列表
      type: command
      # 同 product-normal.commands
      commands:
        - '[console]lp user %player% parent add vip'

# 爱发电API设置，用户ID 和 API Token 到开发者中心获取
# https://afdian.com/dashboard/dev
api:
  user_id: ''
  token: ''
