name: SweetAfdian
version: '${version}'
main: top.mrxiaom.sweet.afdian.SweetAfdian
api-version: 1.13
softdepend: [ PlaceholderAPI ]
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetafdian:
    description: 'The main command of SweetAfdian'
    aliases: [ safd, sponsor ]
